# Generated by Django 3.2.4 on 2021-07-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodelform',
            name='created_at',
        ),
    ]
