# Generated by Django 3.2.4 on 2021-07-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_remove_quizmodelform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodelform',
            name='input1',
            field=models.CharField(max_length=255, null=True, verbose_name='入力例1'),
        ),
        migrations.AddField(
            model_name='quizmodelform',
            name='input2',
            field=models.CharField(max_length=255, null=True, verbose_name='入力例2'),
        ),
        migrations.AddField(
            model_name='quizmodelform',
            name='input3',
            field=models.CharField(max_length=255, null=True, verbose_name='入力例3'),
        ),
        migrations.AddField(
            model_name='quizmodelform',
            name='output1',
            field=models.CharField(max_length=255, null=True, verbose_name='出力例1'),
        ),
    ]
