# Generated by Django 3.2.4 on 2021-07-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20210707_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodelform',
            name='output2',
            field=models.CharField(max_length=255, null=True, verbose_name='出力例2'),
        ),
        migrations.AddField(
            model_name='quizmodelform',
            name='output3',
            field=models.CharField(max_length=255, null=True, verbose_name='出力例3'),
        ),
    ]
